### ISSUE TITLE
error in tf.concat

### ISSUE THREAD

**Issue by pritamqu** [matteson/tensorflow-minibatch-discriminator#1]
Hi I was trying the example you gave with an image size of (none, 128, 128, 3)
it's giving an error here:

tf.concat(1, [convSummary, miniBatchSummary])
Shapes (2, ?, 1) and () are incompatible

also, I didn't understand why are you concating with 1!! please let me know if I am missing something!!

**Comment by pritamqu** [comment]
> Hi I was trying the example you gave with an image size of (none, 128, 128, 3)
> it's giving an error here:
> 
> tf.concat(1, [convSummary, miniBatchSummary])
> Shapes (2, ?, 1) and () are incompatible
> 
> also, I didn't understand why are you concating with 1!! please let me know if I am missing something!!

I think it should be tf.concat([convSummary, miniBatchSummary], axis = 1)

**Comment by andrew-matteson** [comment]
This small demo is based on a tensorflow version that is quite old. The API has changed quite a bit since then, especially with the move to 2.0. I suspect that's the source of the issue, but don't have the time to really dig into at the moment. 

Thanks for the suggestion.
